<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dd2Autobattler\Dd2Autobattler.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.3" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCore)\BepInEx.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCore)\0Harmony.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameManaged)\UnityEngine.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManaged)\UnityEngine.CoreModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(GameManaged)\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GameManaged)\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="IronCrown">
      <HintPath>$(GameManaged)\IronCrown.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GameManaged)\Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
